
all_civs = ['CIVILIZATION_AMERICA', 'CIVILIZATION_ARABIA', 'CIVILIZATION_ASSYRIA', 'CIVILIZATION_AUSTRALIA',
            'CIVILIZATION_AUSTRIA', 'CIVILIZATION_AZTEC', 'CIVILIZATION_BABYLON', 'CIVILIZATION_BRAZIL',
            'CIVILIZATION_BYZANTIUM', 'CIVILIZATION_CARTHAGE', 'CIVILIZATION_CELTS', 'CIVILIZATION_CHINA',
            'CIVILIZATION_CREE', 'CIVILIZATION_DENMARK', 'CIVILIZATION_EGYPT', 'CIVILIZATION_ENGLAND',
            'CIVILIZATION_ETHIOPIA', 'CIVILIZATION_FRANCE', 'CIVILIZATION_GEORGIA', 'CIVILIZATION_GERMANY',
            'CIVILIZATION_GREECE', 'CIVILIZATION_HUNS', 'CIVILIZATION_INCA', 'CIVILIZATION_INDIA',
            'CIVILIZATION_INDONESIA', 'CIVILIZATION_IROQUOIS', 'CIVILIZATION_JAPAN', 'CIVILIZATION_KHMER',
            'CIVILIZATION_KONGO', 'CIVILIZATION_KOREA', 'CIVILIZATION_MACEDON', 'CIVILIZATION_MAPUCHE',
            'CIVILIZATION_MAYA', 'CIVILIZATION_MONGOLIA', 'CIVILIZATION_MOROCCO', 'CIVILIZATION_NETHERLANDS',
            'CIVILIZATION_NORWAY', 'CIVILIZATION_NUBIA', 'CIVILIZATION_OTTOMAN', 'CIVILIZATION_PERSIA',
            'CIVILIZATION_POLAND', 'CIVILIZATION_POLYNESIA', 'CIVILIZATION_PORTUGAL', 'CIVILIZATION_ROME',
            'CIVILIZATION_RUSSIA', 'CIVILIZATION_SCOTLAND', 'CIVILIZATION_SCYTHIA', 'CIVILIZATION_SHOSHONE',
            'CIVILIZATION_SIAM', 'CIVILIZATION_SONGHAI', 'CIVILIZATION_SPAIN', 'CIVILIZATION_SUMERIA',
            'CIVILIZATION_SWEDEN', 'CIVILIZATION_VENICE', 'CIVILIZATION_ZULU', 'CIVILIZATION_MALI',
            'CIVILIZATION_MAORI', 'CIVILIZATION_HUNGARY', 'CIVILIZATION_CANADA', 'CIVILIZATION_PHOENICIA',
            'CIVILIZATION_GRAN_COLOMBIA']
all_civs.sort()

all_civs_plus_none = ["None"] + all_civs
